<?php
require_once('../vendor/autoload.php'); // Ensure Composer's autoload is included
include '../Backend/db.php'; // Include your database connection

// Fetch applications data
$sqlApplications = "SELECT u.surname, u.other_names, u.email, c.name AS course_name, a.status, a.application_date
                    FROM applications a
                    JOIN users u ON a.user_id = u.id
                    JOIN courses c ON a.course_id = c.id";
$resultApplications = $conn->query($sqlApplications);

// Prepare an empty array to store applications
$applications = [];
if ($resultApplications->num_rows > 0) {
    while ($row = $resultApplications->fetch_assoc()) {
        $applications[] = $row;
    }
}

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Application');
$pdf->SetTitle('Application Report');
$pdf->SetSubject('List of Applications');
$pdf->SetKeywords('TCPDF, PDF, application, report');

// set default header data
$pdf->SetHeaderData('', '', 'Application Report', 'Generated by Your Application');

// set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// add a page
$pdf->AddPage();

// set font
$pdf->SetFont('helvetica', '', 12);

// output the HTML content
$html = '<h1>Application Report</h1>';
$html .= '<table border="1" cellpadding="5">';
$html .= '<thead><tr>
            <th>Surname</th>
            <th>Other Names</th>
            <th>Email</th>
            <th>Course Name</th>
            <th>Status</th>
            <th>Application Date</th>
        </tr></thead>';
$html .= '<tbody>';

foreach ($applications as $application) {
    $html .= '<tr>';
    $html .= '<td>' . htmlspecialchars($application['surname']) . '</td>';
    $html .= '<td>' . htmlspecialchars($application['other_names']) . '</td>';
    $html .= '<td>' . htmlspecialchars($application['email']) . '</td>';
    $html .= '<td>' . htmlspecialchars($application['course_name']) . '</td>';
    $html .= '<td>' . htmlspecialchars($application['status']) . '</td>';
    $html .= '<td>' . htmlspecialchars($application['application_date']) . '</td>';
    $html .= '</tr>';
}

$html .= '</tbody></table>';

$pdf->writeHTML($html, true, false, true, false, '');

//Close and output PDF document
$pdf->Output('application_report.pdf', 'D');

// Close the database connection
$conn->close();
?>
